export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAIL = "FETCH_ITEMS_FAIL";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_ITEM_AMOUNT = "INCREASE_ITEM_AMOUNT";
export const DECRIASE_ITEM_AMOUNT = "DECRIASE_ITEM_AMOUNT";

export const ADD_USER_SHIPPING_INFO = "ADD_USER_SHIPPING_INFO";
export const MAKE_PURCHASE = "MAKE_PURCHASE";
export const MAKE_PURCHASE_SUCCESS = "MAKE_PURCHASE_SUCCESS";

export const RESET_ITEMS_STATE = "RESET_ITEMS_STATE";
export const RESET_USER_STATE = "RESET_USER_STATE";

export const ACTION_AUTHED = "ACTION_AUTHED";
export const ACTION_LOGOUT = "ACTION_LOGOUT"
